### ISSUE TITLE
  could not find function "plotSampledTimingPatterns"

### ISSUE THREAD

**Issue by paoloRais** [mplatzer/BTYDplus#47]
On a fresh BTYDPlus install I am not able to run demo("mbg-cnbd-k"). I get the following error message:

> > #' Plot Timing Patterns of a few sampled customers
> > plotSampledTimingPatterns(groceryElog, T.cal = "2006-12-31")
> Error in eval(expr, envir, enclos) : 
>   could not find function "plotSampledTimingPatterns"

**Comment by mplatzer** [comment]
thanks for the bug report. this is now fixed in `master`, plus there is a `0.11.3` hotfix release
