### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by paoloRais** [mplatzer/BTYDplus#49]
More a proposal than an issue: I wrote a dockerfile for BTYDplus, any interest to integrate it in the project?

**Comment by mplatzer** [comment]
sounds interesting. could you share that file here via this ticket?

**Comment by paoloRais** [comment]
Sure, here it is:
`
## Adapted from zamora/r-devtools
## Start with the official rocker image (lightweight Debian)
FROM rocker/r-base:latest

# Install external dependencies
RUN apt-get update -qq \
 && apt-get install -t unstable -y --no-install-recommends \
 libcurl4-openssl-dev \
 libssl-dev \
 libsqlite3-dev \
 libxml2-dev \
 qpdf \
 vim \
 libgsl-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/ \
 && rm -rf /tmp/downloaded_packages/ /tmp/*.rds

# Install devtools and testthat
#RUN Rscript -e 'install.packages(c("devtools","testthat"),dependencies = TRUE)'
RUN install2.r --error \
  devtools \
  testthat \
  gsl
RUN Rscript -e 'devtools::install_github("mplatzer/BTYDplus", dependencies=TRUE)'
`

Then you will need to forward X11 for the plotting tools as explained in:
http://stackoverflow.com/a/25334301/5251962

**Comment by mplatzer** [comment]
thanks Paolo! I have only little experience with Docker, but shouldn't that file then rather be hosted at DockerHub? as of now, I am not convinced that each and every R package should include (and maintain) that same docker file template.

**Comment by paoloRais** [comment]
I think it is a matter of choice - I agree that Docker is not that common in the R community, but I have seen quite a lot of Python packages that maintain one and I think it is a nice idea for installing/testing in isolation, especially for packages that have a lot of dependencies, hence my initial question.

In my opinion the cons are:
- Not many users will use that
- Not sure if there is any CRAN requirement on that
- Not sure how to include it in the CI framework

While the pros are:
- It saves time to whoever may want to test/deploy the package without going through the whole R + dependencies installation process.
- It allows for a generally easier testing & deployment
-It keeps the dockerfile here rather than in an additional location
- It is a single lightweight additional file and it does not affect in any way the users not using docker

**Comment by mplatzer** [comment]
close as wontfix
