### ISSUE TITLE
Add "m.x" to elog2cbs() output

### ISSUE THREAD

**Issue by msinjin** [mplatzer/BTYDplus#53]
Calculation of the average spend per repeat transaction in the calibration period ("m.x.") cannot be derived from the cbs created by elog2cbs() because "sales" appears to be a vector of TOTAL sales (ie. first transaction is NOT removed). 

It would be great to provide "sales.x" (repeat sales only, first transaction removed) so one can calculate m.x = sales.x/x; and/or m.x.

**Comment by mplatzer** [comment]
many thanks @msinjin for the suggestion! I've made that addition now.

**Comment by msinjin** [comment]
Thanks for this! The addition of sales.x makes my life a lot easier (and my code a lot faster).

Best,
Mark
