### ISSUE TITLE
Throw error for empty data frame?

### ISSUE THREAD

**Issue by JakeRuss** [mplatzer/BTYDplus#58]
I recently encountered the following error message, *Error:_ T.tot >= min(elog$date) is not TRUE*, which led me to investigate whether my dates were correct inside of a list of data frames. Finally, I made the connection that some of my data frames were empty, which prompted the message.

It might be worth adding a check for whether the supplied data frame is empty, and give a more informative error message. Do you agree? If so, I'll file a pull request.

```
library(BTYDplus)
df <- data.frame(cust = character(), date = as.Date(character()))
elog2cbs(df)
```

**Comment by mplatzer** [comment]
Absolutely agree. Happy to consider your pull request, if you submit one.


Am 14.07.2017 19:01 schrieb "Jake Russ" <notifications@github.com>:
