### ISSUE TITLE
bgcnbd.PlotTrackingCum / mbgcnbd.PlotTrackingCum

### ISSUE THREAD

**Issue by paullevchuk** [mplatzer/BTYDplus#64]
Just downloaded the latest version of package via command: 
devtools::install_github("mplatzer/BTYDplus", dependencies=TRUE)

While I am trying to call subj functions I got an error:
Error in .Call("_BTYDplus_xbgcnbd_exp_cpp", PACKAGE = "BTYDplus", params,  : 
  "_BTYDplus_xbgcnbd_exp_cpp" not available for .Call() for package "BTYDplus".

It seems like this function is not public anymore.

**Comment by mplatzer** [comment]
I just made a clean install from github myself, but can't reproduce the issue. Also it would be weird, since these methods are covered by automated tests. which R version, package versions are you using? can you run https://github.com/mplatzer/BTYDplus/blob/master/tests/testthat/test-bg-cnbd-k.R ?

**Comment by mplatzer** [comment]
is this still an issue?

**Comment by paullevchuk** [comment]
I removed package, restarted RStudio, then reinstall package from github and now everything is OK.
