### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by NahuelGrasso** [mplatzer/BTYDplus#68]
Hi, I wonder if there is a python version of this package.
Thanks,
Nahue

**Comment by mplatzer** [comment]
there is no python version of BTYDplus available, and I am also not planning one. which model would you be interested in particular? and what keeps you from using R?

**Comment by NahuelGrasso** [comment]
Perfect, just to know!. I've been using the R version and since there is a chance to move towards a python server, I was curious about it.
