### ISSUE TITLE
data.table.rdb is corrupt error on installing BTYDplus

### ISSUE THREAD

**Issue by msinjin** [mplatzer/BTYDplus#69]
I've run into this problem before, and recall solving it, but am at a loss today.

I get this error when loading BTYDplus (`library(BTYDplus)`) 

`Error: package or namespace load failed for 'data.table' in get(Info[i, 1], envir = env):
 lazy-load database '/home/mark/R/x86_64-pc-linux-gnu-library/3.4/data.table/R/data.table.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1
`

I've tried removing `data.table` and `BTYDplus`, and reinstalling, but no luck.

I've installed with `devtools::install_github("mplatzer/BTYDplus", dependencies=TRUE)`

**Comment by msinjin** [comment]
The problem might be with `devtools::install_github` according to others on the web. Removing (`rm`) the supposedly-offending package (`data.table` in my case) and a restart before trying again seems to have worked.

**Comment by mplatzer** [comment]
Great to hear, and thanks for sharing!
